name: build-and-integration-test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 1
      matrix:
        dotnet: ['8.0.x']

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: ./restore.sh

      - name: Build
        run: ./build.sh

      - name: Test
        env:
          RYFT_INTEGRATION_TESTS_API_KEY: ${{ secrets.RYFT_INTEGRATION_TESTS_API_KEY }}
          RYFT_CUSTOMER_ID: ${{ secrets.RYFT_CUSTOMER_ID }}
          RYFT_EVENT_ID: ${{ secrets.RYFT_EVENT_ID }}
          RYFT_HOSTED_ACCOUNT_ID: ${{ secrets.RYFT_HOSTED_ACCOUNT_ID }}
          RYFT_NON_HOSTED_ACCOUNT_ID: ${{ secrets.RYFT_NON_HOSTED_ACCOUNT_ID }}
          RYFT_PAYMENT_METHOD_ID: ${{ secrets.RYFT_PAYMENT_METHOD_ID }}
          RYFT_PLATFORM_FEE_ID: ${{ secrets.RYFT_PLATFORM_FEE_ID }}
        run: ./integration-test.sh
