name: build-and-test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet:
          - 8.0.x

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: ./restore.sh

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./test.sh
