name: publish-to-nuget

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        dotnet: ['8.0.x']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release
        
      - name: Unit tests
        run: ./test.sh

      - name: Package
        run: dotnet pack --no-build --configuration Release --output nuget

      - name: Upload to Nuget
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "nuget.org" --skip-duplicate
